/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\college.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function College(props) {
  const { nodes, materials } = useGLTF('/college-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.799, 0.063 - 150, -2.312]} rotation={[0, 0.972, 0]} scale={0.026}>
        <mesh geometry={nodes.Mesh707.geometry} material={materials['Black Metallic']} />
        <mesh geometry={nodes.Mesh707_1.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh707_2.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Mesh707_3.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Mesh707_4.geometry} material={materials.PaletteMaterial003} />
      </group>
    </group>
  )
}

useGLTF.preload('/college-transformed.glb')
