/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\paper.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Paper(props) {
  const { nodes, materials } = useGLTF('/paper-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane015.geometry} material={materials['paper.002']} position={[2.34, 0.122 - 150, 2.797]} rotation={[Math.PI, -0.467, Math.PI]} scale={[10.456, 0.104, 10.456]} />
    </group>
  )
}

useGLTF.preload('/paper-transformed.glb')
