/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\table.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.277, -13.014 - 150, 0.109]} scale={18.163}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/table-transformed.glb')
